version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test_db
      JWT_SECRET: test_jwt_secret
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npm ci && npm test -- --runInBand"]
    # keep container logs so we can see test output
    tty: true
    stdin_open: true

volumes:
  mysql_test_data:
