version: "3.9"

services:
  backend:
    build: .
    container_name: backend_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_PORT: 3306
      JWT_SECRET: your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
